// <auto-generated />
namespace e_Office.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class init212 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init212));
        
        string IMigrationMetadata.Id
        {
            get { return "201910210809293_init212"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
